# https://docs.github.com/en/actions

on: [push, pull_request]
jobs:
  ci:
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.11.0
      - run: zig fmt --check .
      - run: zig build
      - run: zig build test
